apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: react-app-ns
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      # Pod-level security context
      securityContext:
        # runAsUser: 11100       # High UID
        # runAsGroup: 11100
        # fsGroup: 11100
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: react-app-sa   # Non-default service account
      automountServiceAccountToken: false
      containers:
        - name: react-app
          image: ghcr.io/<org>/<repo>@sha256:<digest>
          ports:
            - containerPort: 80
          # Container-level security context
          securityContext:
            runAsNonRoot: true
            runAsUser: 11100        # High UID matching Dockerfile
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          # Liveness probe
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          # Readiness probe
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: react-app-sa
  namespace: react-app-ns
automountServiceAccountToken: false

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: react-app-netpol
  namespace: react-app-ns
spec:
  podSelector:
    matchLabels:
      app: react-app
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}  # Only allow traffic from same namespace (tighten if needed)
      ports:
        - protocol: TCP
          port: 80
  egress:
    - to:
        - podSelector: {}  # Only allow traffic within namespace
      ports:
        - protocol: TCP
          port: 80
