apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: react-app-ns   # Dedicated namespace
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      # Pod-level security context
      securityContext:
        runAsUser: 1000        # High UID
        runAsGroup: 3000
        fsGroup: 2000
      automountServiceAccountToken: false  # Disable default SA token
      containers:
        - name: react-app
          image: ghcr.io/<org>/<repo>@sha256:<digest>  # Immutable image by digest
          ports:
            - containerPort: 80
          # Container-level security context
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          # Resource requests & limits
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          # Liveness & readiness probes
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: react-app-network-policy
  namespace: react-app-ns
spec:
  podSelector:
    matchLabels:
      app: react-app
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from: []   # Restrict ingress, can add allowed sources
  egress:
    - to: []     # Restrict egress, can add allowed destinations
