apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: react-app-ns
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      # Pod-level security context
      securityContext:
        runAsUser: 1000         # Use high UID to avoid host conflicts
        runAsGroup: 3000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault  # Use default seccomp profile
      containers:
        - name: react-app
          # Use immutable image by digest
          image: ghcr.io/<org>/<repo>@sha256:<digest>
          ports:
            - containerPort: 80
          # Container-level security context
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          # Liveness & Readiness probes
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          # Resource requests & limits
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      serviceAccountName: react-app-sa  # Avoid mounting default service account tokens
