name: CI-CD-Security-React

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.get-digest.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Build Docker image
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:latest
          docker build -t $IMAGE_NAME .
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}

      - name: Get image digest
        id: get-digest
        run: |
          digest=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ env.IMAGE_NAME }})
          echo "::set-output name=digest::$digest"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RG }}
          cluster-name: ${{ secrets.AKS_CLUSTER }}

      - name: Update deployment.yaml with digest
        run: |
          sed -i "s|image: ghcr.io/.*/.*:latest|image: ${{ needs.build-and-scan.outputs.digest }}|" k8s/deployment.yaml

      - name: Deploy to AKS
        run: kubectl apply -f k8s/deployment.yaml
